{
 "title": "Datasource tests - Elasticsearch complex with template variables",
 "tags": [
  "gdev",
  "elasticsearch",
  "datasource-test"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"hostname\"}"
   },
   {
    "name": "level_by_hostname",
    "query": "{\"find\": \"terms\", \"field\": \"level\", \"query\": \"hostname:$hostname\"}"
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Date histogram with count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Basic - interval 1m + min doc count 50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 50 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic - interval 5m + trim edges = 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 10 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Date histogram with metric aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Basic with aggregation - avg - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic with aggregation - percentiles - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {
          "percents": [
           "25",
           "50",
           "75",
           "95",
           "99"
          ]
         },
         "type": "percentiles"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic with aggregation - min - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "min" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic with aggregation - sum - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic with aggregation - max - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "max" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic with aggregation - extended stats - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "meta": {
          "avg": true,
          "count": true,
          "max": true,
          "min": true,
          "std_deviation": true,
          "std_deviation_bounds_lower": true,
          "std_deviation_bounds_upper": true,
          "sum": true
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic with aggregation - unique count - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "cardinality" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Date histogram with moving functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "moving function - count - interval 5m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        },
        {
         "field": "1",
         "id": "4",
         "pipelineAgg": "1",
         "settings": { "script": "MovingFunctions.max(values)", "window": "10" },
         "type": "moving_fn"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "moving function - unique count - interval 5m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "hide": false,
         "id": "1",
         "type": "cardinality"
        },
        {
         "field": "1",
         "id": "4",
         "pipelineAgg": "1",
         "settings": { "script": "MovingFunctions.max(values)", "window": "10" },
         "type": "moving_fn"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "moving function - max - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "max" },
        {
         "field": "1",
         "id": "4",
         "pipelineAgg": "1",
         "settings": { "script": "MovingFunctions.max(values)", "window": "10" },
         "type": "moving_fn"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "moving function - avg - interval 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" },
        {
         "field": "1",
         "id": "4",
         "pipelineAgg": "1",
         "settings": { "script": "MovingFunctions.max(values)", "window": "10" },
         "type": "moving_fn"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "moving function - sum - interval 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "float", "id": "1", "type": "sum" },
        {
         "field": "1",
         "id": "4",
         "pipelineAgg": "1",
         "settings": { "script": "MovingFunctions.max(values)", "window": "10" },
         "type": "moving_fn"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Date histogram with derivative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "derivative - unique count - interval 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "precision_threshold": "10" }, "type": "cardinality" },
        { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "derivative - max - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "max" },
        { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "derivative - sum - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "float", "id": "1", "type": "sum" },
        { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Date histogram with cumulative sum aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "cumulative sum - unique count - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "precision_threshold": "10" }, "type": "cardinality" },
        { "field": "1", "id": "4", "pipelineAgg": "1", "type": "cumulative_sum" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "cumulative sum - avg - interval 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "float", "id": "1", "settings": { "script": "_value * 0.1" }, "type": "avg" },
        { "field": "1", "id": "4", "pipelineAgg": "1", "type": "cumulative_sum" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "cumulative sum - count - interval 10s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "1", "id": "4", "pipelineAgg": "1", "type": "cumulative_sum" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "cumulative sum - min - interval 1m - trim edges 100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "trimEdges": "100" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "min" },
        { "field": "1", "id": "4", "pipelineAgg": "1", "type": "cumulative_sum" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Date histogram with bucket script aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "count * avg - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": true,
         "id": "1",
         "type": "count"
        },
        {
         "field": "value",
         "hide": true,
         "id": "4",
         "type": "avg"
        },
        {
         "id": "5",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" },
          { "name": "var2", "pipelineAgg": "4" }
         ],
         "settings": { "script": "params.var1 * params.var2" },
         "type": "bucket_script"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count * 1000 - interval 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": true,
         "id": "1",
         "type": "count"
        },
        {
         "id": "3",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" }
         ],
         "settings": { "script": "params.var1 * 1000" },
         "type": "bucket_script"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count * 1000 - interval 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "alias": "Alias",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": true,
         "id": "1",
         "type": "count"
        },
        {
         "id": "3",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" }
         ],
         "settings": { "script": "params.var1 * 1000" },
         "type": "bucket_script"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Multiple metrics and aggregations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "count/average with triple terms agg - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "metric",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "level",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        },
        { "field": "value", "id": "3", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count/average with triple terms agg - interval auto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "alias": "{{hostname}} - {{metric}} - {{level}}",
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "metric",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "level",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        },
        { "field": "value", "id": "3", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Terms order by simple aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terms order by unique count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "cardinality" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by Term value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by Doc Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by avg with alias",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "alias": "hostname: {{hostname}}",
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Terms order by extended stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terms order by extended stats (std dev lower)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[std_lower]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "meta": {
          "std_deviation_bounds_lower": true,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (std dev)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[std_lower]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "meta": {
          "std_deviation": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "settings": { "script": "_value * 4", "sigma": "3" },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[sum]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "float",
         "id": "1",
         "meta": {
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": true
         },
         "settings": { "script": "_value * 4", "sigma": "3" },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (count,avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[count]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "float",
         "id": "1",
         "meta": {
          "avg": true,
          "count": true,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "settings": { "script": "_value * 4", "sigma": "3" },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Terms order by percentile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terms order by percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[25.0]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "float",
         "id": "1",
         "settings": {
          "percents": [
           "25",
           "50",
           "75",
           "95",
           "99"
          ],
          "script": "_value * 2"
         },
         "type": "percentiles"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by percentile (99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Inline scripts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Old & new script format",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "alias": "New script format",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "script": "_value * 2" }, "type": "avg" }
       ],
       "timeField": "@timestamp"
      },
      {
       "alias": "Old script format",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "script": "_value * 1.5" }, "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw data and documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw documents in table",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_document" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Raw data",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Using template variables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$hostname count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "hostname: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$hostname average float",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "float", "id": "1", "type": "avg" }
       ],
       "query": "hostname: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$hostname and $level_by_hostname count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "hostname: $hostname AND level: $level_by_hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$hostname and $level_by_hostname average float",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "float", "id": "1", "type": "avg" }
       ],
       "query": "hostname: $hostname AND level: $level_by_hostname",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}